---
- name: upgrade all packages(yum)
  when: ansible_os_family == 'RedHat'
  yum:
    name: '*'
    state: latest

- name: upgrade all packages(apt)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: dist 
    update_cache: yes

- name: added key to ssh
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file','/home/user/.ssh/id_rsa.pub') }}"

